DO i = iMin, iMax
    DO j = bMin, bMax
        Area(i) = 0.0_rDef                   
        Area1(i) = 0.0_rDef                  
        x1(i) = 0.0_rDef                     
        Source_Fac(i) = 0.0_rDef             
        Q_n(i, j) = 0.0_rDef              
        Q_np1(i, j) = 0.0_rDef            
        Q_nm1(i, j) = 0.0_rDef            
        Q_nm2(i, j) = 0.0_rDef            
        dQdTau(i, j) = 0.0_rDef           
        dAdZi(i) = 0.0_rDef                  
        RHS(i, j) = 0.0_rDef              
        E_GPT(i, j) = 0.0_rDef            
        E(i, j) = 0.0_rDef                
        Dis(i, j) = 0.0_rDef              
        Q_np1_k(i, j) = 0.0_rDef          
        Mean_FFT1(i) = 0.0_rDef              
        Q_np1_kp1(i, j) = 0.0_rDef        
        Exact(i, j) = 0.0_rDef            
        Delta_Q_star2(i, j) = 0.0_rDef    
        Delta_Q_star(i, j) = 0.0_rDef     
        Delta_Q(i, j) = 0.0_rDef          
        Jac_Curv(i) = 0.0_rDef               
        Inv_Jac_Curv(i) = 0.0_rDef           
        Vel(i) = 0.0_rDef                    
        Vel_Mean(i)     = 0.0_rDef               
        Vel_Pet(i)      = 0.0_rDef                
        Den(i)          = 0.0_rDef                    
        Den_Mean(i)     = 0.0_rDef               
        Den_Pet(i)      = 0.0_rDef                
        Pres(i)         = 0.0_rDef                   
        Pres_Mean(i)    = 0.0_rDef              
        Pres_Pet(i)     = 0.0_rDef               
        dXdt(i)         = 0.0_rDef                   
        dZidX(i)        = 0.0_rDef                  
    END DO
END DO
